name: bukkitstaff
main: me.jophestus.bukkitstaff.bukkitstaff
version: 6.5
description: bukkitstaff
commands:
    EvilSeph:
        description: 'Sends you an awesome message'
        usage: '/command'
    lukegb:
        description: 'Sends you an awesome message'
        usage: '/command'
    Dinnerbone:
        description: 'Sends you an awesome message'
        usage: '/command'
    TnT:
        description: 'Sends you an awesome message'
        usage: '/command'
    mbaxter:
        description: 'Sends you an awesome message'
        usage: '/command'
    c0mp:
        description: 'Sends you an awesome message'
        usage: '/command'
    Butkicker12:
        description: 'Sends you an awesome message'
        usage: '/command'
    obnoxint:
        description: 'Sends you an awesome message'
        usage: '/command'
    Jacek:
        description: 'Sends you an awesome message'
        usage: '/command'
    NodinChan:
        description: 'Sends you an awesome message'
        usage: '/command'
    Gravity:
        description: 'Sends you an awesome message'
        usage: '/command'
    np98765:
        description: 'Sends you an awesome message'
        usage: '/command'
    Lolmewn:
        description: 'Sends you an awesome message'
        usage: '/command'
    chaseoes:
        description: 'Sends you an awesome message'
        usage: '/command'
    Deathmarine:
        description: 'Sends you an awesome message'
        usage: '/command'
    feildmaster:
        description: 'Sends you an awesome message'
        usage: '/command'
    lDucks:
        description: 'Sends you an awesome message'
        usage: '/command'
    evilmidget38:
        description: 'Sends you an awesome message'
        usage: '/command'
    Wolvereness:
        description: 'Sends you an awesome message'
        usage: '/command'
    slipcor:
        description: 'Sends you an awesome message'
        usage: '/command'
    Iaccidentally:
        description: 'Sends you an awesome message'
        usage: '/command'
    hawkfalcon:
        description: 'Sends you an awesome message'
        usage: '/command'
    drtshock:
        description: 'Sends you an awesome message'
        usage: '/command'
    Eviltechie:
        description: 'Sends you an awesome message'
        usage: '/command'
    lol768:
        description: 'Sends you an awesome message'
        usage: '/command'
    necrodoom:
        description: 'Sends you an awesome message'
        usage: '/command'
    Jade:
        description: 'Sends you an awesome message'
        usage: '/command'
    Iroh:
        description: 'Sends you an awesome message'
        usage: '/command'
    toothplck1:
        description: 'Sends you an awesome message'
        usage: '/command'
    recon88:
        description: 'Sends you an awesome message'
        usage: '/command'
    ZeusAllMighty11:
        description: 'Sends you an awesome message'
        usage: '/command'
    -_Husky_-:
        description: 'Sends you an awesome message'
        usage: '/command'
    kezz101:
        description: 'Sends you an awesome message'
        usage: '/command'
    chasechocolate:
        description: 'Sends you an awesome message'
        usage: '/command'
    gomeow:
        description: 'Sends you an awesome message'
        usage: '/command'
    DSH105:
        description: 'Sends you an awesome message'
        usage: '/command'
    Hoolean:
        description: 'Sends you an awesome message'
        usage: '/command'
    squidicuz:
        description: 'Sends you an awesome message'
        usage: '/command'
author: JOPHESTUS
