name: bukkitstaff
main: me.jophestus.bukkitstaff.bukkitstaff
version: 5.0
description: bukkitstaff
commands:
    EvilSeph
    lukegb
    Dinnerbone
    TnT
    NuclearW
    mbaxter
    c0mp
    Butkicker12
    obnoxint
    Jacek
    krinsdeath
    NodinChan
    Milkywayz
    Gravity
    np98765
    Lolmewn
    sablednah
    chaseoes
    Zarius
    Deathmarine
    feildmaster
    lDucks
    evilmidget38
    jkcclemens
    slipcor
    --GJ--
    Iaccidentally
    hawkfalcon
    drtshock
    Eviltechie
    lol768
    toothplck1
    gomeow
author: JOPHESTUS, Chaseoes